# Generated by Django 4.0.5 on 2022-08-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_list_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='list_available',
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_available',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
