# Generated by Django 4.0.5 on 2022-08-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_listing_list_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_available',
            field=models.BooleanField(default=True),
        ),
    ]
